# Copyright (c) 2007. RevenueMed, Inc. All rights reserved.

class AddDefaultEobErrors < ActiveRecord::Migration
  def self.up
    error_list = [
      {:severity => 0, :error_type => "Correct", :code => "COR"},
      #{:severity => 9, :error_type => "Health Insurance Coverage Wrong Selection", :code => "HCW"},
      #{:severity => 9, :error_type => "Health Insurance Coverage Unchecked", :code => "HCU"},
      {:severity => 9, :error_type => "Insured' s Id Incorrect", :code => "III"},
      {:severity => 8, :error_type => "Patient's Name First/Last name shuffle", :code => "PNS"},
      {:severity => 7, :error_type => "Patient's Name Incorrect", :code => "PNI"},
      {:severity => 7, :error_type => "Patient's Name Middle Initial Missing", :code => "PMM"},
      {:severity => 7, :error_type => "Patient's Name Suffix Missing/Incorrect", :code => "PSM / PSI"},
      {:severity => 7, :error_type => "Patient's DOB Incorrect", :code => "PDI"},
      {:severity => 7, :error_type => "Patient's Gender Wrong Selection", :code => "PGW"},
      {:severity => 7, :error_type => "Insured's Name First/Last name shuffle", :code => "INS"},
      {:severity => 5, :error_type => "Insured's Name Incorrect", :code => "INI"},
      {:severity => 5, :error_type => "Insured's Name Middle Initial Missing", :code => "IMI"},
      {:severity => 8, :error_type => "Insured's Name Suffix Missing/Incorrect", :code => "ISM / ISI"},
      {:severity => 8, :error_type => "Street Address Incorrect", :code => "CYI"},
      {:severity => 7, :error_type => "City Incorrect", :code => "CHL"},
      {:severity => 7, :error_type => "State Wrong selection", :code => "STW"},
      {:severity => 5, :error_type => "Zip code Incorrect", :code => "ZPI"},
      {:severity => 5, :error_type => "Phone number Incorrect", :code => "PHI"},
      {:severity => 7, :error_type => "Patient Relationship Wrong Selection", :code => "PRI"},
      {:severity => 7, :error_type => "Patient Status-Wrong Selection", :code => "PSW"},
      #{:severity => 5, :error_type => "Other Insured's Name First/Last name shuffle", :code => "ONS"},
      #{:severity => 5, :error_type => "Other Insured's Name Incorrect", :code => "ONI"},
      #{:severity => 5, :error_type => "Other Insured's Name Middle Initial Missing", :code => "OMM"},
      #{:severity => 10, :error_type => "Other Insured's Name Suffix Missing/Incorrect", :code => "OSM/OSI"},
      #{:severity => 7, :error_type => "Other Insured's Policy Number Incorrect", :code => "OPI"},
      #{:severity => 7, :error_type => "Other Insured's DOB Incorrect", :code => "ODI"},
      #{:severity => 10, :error_type => "Other Insured's Gender Wrong Selection", :code => "OGW"},
      #{:severity => 10, :error_type => "Employers' Name Missing", :code => "MUL"},
      #{:severity => 8, :error_type => "Employers' Name Incorrect", :code => "ENI"},
      {:severity => 8, :error_type => "Insurance Plan Name Missing", :code => "IPM"},
      {:severity => 8, :error_type => "Insurance Plan Name Incorrect", :code => "IPI"},
      {:severity => 8, :error_type => "Patient's Condition any wrong selection", :code => "PCW"},
      {:severity => 8, :error_type => "Auto-Accident (Place) Incorrect", :code => "AAI"},
      #{:severity => 7, :error_type => "Reserved For Local Use Missing", :code => "LUM"},
      #{:severity => 7, :error_type => "Reserved For Local Use Incorrect", :code => "LUI"},
      {:severity => 8, :error_type => "Insured's Policy Group Number Missing", :code => "IGM"},
      {:severity => 8, :error_type => "Insured's Policy Group Number Incorrect", :code => "IGI"},
      {:severity => 8, :error_type => "Insured's DOB Incorrect", :code => "IDI"},
      {:severity => 7, :error_type => "Insured's Gender Wrong Selection", :code => "IGW"},
      {:severity => 5, :error_type => "SOF Wrong Selection", :code => "SGW"},
      {:severity => 8, :error_type => "Date of Signature Incorrect", :code => "DSI"},
      #{:severity => 7, :error_type => "Date of Signature Missing", :code => "DSM"},
      {:severity => 7, :error_type => "Date of Current Incorrect", :code => "DCI"},
      {:severity => 5, :error_type => "Date of Current Missing", :code => "DCM"},
      {:severity => 5, :error_type => "Same / Similar Illness Date - Incorrect", :code => "SDI"},
      {:severity => 8, :error_type => "Period of Unfitness Incorrect", :code => "PUI"},
      {:severity => 8, :error_type => "Period of Unfitness Missing", :code => "PUM"},
      {:severity => 7, :error_type => "Referring Provider Name Incorrect", :code => "RPI"},
      {:severity => 8, :error_type => "Referring Provider Name Missing", :code => "RPM"},
      {:severity => 8, :error_type => "Non NPI number Incorrect", :code => "NNI"},
      {:severity => 8, :error_type => "Non NPI number Missing", :code => "NNI"},
      {:severity => 6, :error_type => "NPI Number Incorrect", :code => "NPI"},
      {:severity => 6, :error_type => "NPI Number Missing", :code => "NPM"},
      {:severity => 5, :error_type => "Hospitalization Date Incorrect", :code => "HDI"},
      {:severity => 5, :error_type => "Hospitalization Date Missing", :code => "HDM"},
      #{:severity => 10, :error_type => "Outside Lab  Wrong Selection", :code => "OLW"},
      #{:severity => 10, :error_type => "Outside Lab Charge Incorrect", :code => "LCI"},
      #{:severity => 6, :error_type => "Outside Lab Charge Missing", :code => "LCM"},
      {:severity => 6, :error_type => "Diagnosis Code Incorrect", :code => "DGI"},
      {:severity => 5, :error_type => "Diagnosis Code Missing", :code => "DGM"},
      #{:severity => 5, :error_type => "Medicaid Resubmission Code Incorrect", :code => "MCI"},
      #{:severity => 10, :error_type => "Medicaid Resubmission Code Missing", :code => "MCM"},
      #{:severity => 10, :error_type => "Original Reference No Missing", :code => "ORM"},
      #{:severity => 6, :error_type => "Original Reference No Incorrect", :code => "ORI"},
      {:severity => 5, :error_type => "Prior Authorization No Incorrect", :code => "ANI"},
      {:severity => 5, :error_type => "Prior Authorization No Missing", :code => "ANM"},
      {:severity => 10, :error_type => "DOS Incorrect", :code => "DTI"},
      {:severity => 10, :error_type => "Place of Service Incorrect", :code => "PLI"},
      {:severity => 5, :error_type => "EMG Incorrect", :code => "EMI"},
      {:severity => 5, :error_type => "EMG Missing", :code => "EMM"},
      {:severity => 10, :error_type => "CPT Code Incorrect", :code => "CPI"},
      {:severity => 10, :error_type => "Modifier Incorrect", :code => "MOI"},
      {:severity => 5, :error_type => "Modifier Missing", :code => "MOM"},
      {:severity => 5, :error_type => "Diagnosis Pointer Incorrect", :code => "DPI"},
      {:severity => 10, :error_type => "Charge Incorrect", :code => "CHI"},
      {:severity => 10, :error_type => "Units Missing", :code => "UTM"},
      {:severity => 5, :error_type => "Units Incorrect", :code => "UTI"},
      {:severity => 5, :error_type => "EPSDT Missing", :code => "EPM"},
      {:severity => 0, :error_type => "EPSDT Incorrect", :code => "EPI"},
      {:severity => 9, :error_type => "ID Qualifier Incorrect", :code => "IQI"},
      {:severity => 9, :error_type => "ID Qualifier Missing", :code => "IQM"},
      {:severity => 9, :error_type => "Federal Tax Id No Incorrect", :code => "TDI"},
      {:severity => 8, :error_type => "Tax Id No Wrong Selection", :code => "TDW"},
      {:severity => 7, :error_type => "Patient Account Number Incorrect", :code => "PAI"},
      {:severity => 7, :error_type => "Assignment Acceptance Wrong Selection", :code => "AAW"},
      {:severity => 7, :error_type => "Amount Paid Incorrect", :code => "API"},
      {:severity => 7, :error_type => "Supplier/Physician's Signature Wrong Selection", :code => "SSW"},
      {:severity => 7, :error_type => "Supplier/Physician's Name First/Last name shuffle", :code => "SNS"},
      {:severity => 7, :error_type => "Supplier/Physician's Name Incorrect", :code => "SNI"},
      {:severity => 5, :error_type => "Supplier/Physician's Name Middle Initial Missing", :code => "SMM"},
      {:severity => 5, :error_type => "Supplier/Physician's Name Suffix Missing/Incorrect", :code => "SSM"},
      {:severity => 8, :error_type => "Organization Name  Incorrect", :code => "OZI"},
      {:severity => 8, :error_type => "Billing Provider's Name First/Last name shuffle", :code => "BNS"},
      {:severity => 7, :error_type => "Billing Provider's Name Incorrect", :code => "BNI"},
      {:severity => 7, :error_type => "Billing Provider's Name Middle Initial Missing", :code => "BMM"},
      {:severity => 5, :error_type => "Billing Provider's Name Suffix Missing/Incorrect", :code => "BSM"},
      
    ]
    error_list.each do |e|
      EobError.create(e)
    end
  end

  def self.down
    EobError.delete_all
  end
end
